### ISSUE TITLE
nternal error message: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by riyasoni1** [dominiksta/wournal#10]
{
  "buildInfo": {
    "wournalVersion": "0.0.5",
    "gitVersion": "bd853c1",
    "buildTime": "2024-05-22T13:02:01.525Z",
    "production": true,
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) wournal/0.0.5 Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36"
  },
  "error": {
    "name": "NotFoundError",
    "constructor": "DOMException",
    "message": "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.",
    "stack": "Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n    at UndoActionCanvasElements.undo (file:///C:/Users/ASUS/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2374319)\n    at UndoStack.undo (file:///C:/Users/ASUS/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2376645)\n    at WournalDocument.undo (file:///C:/Users/ASUS/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2382002)\n    at Object.undo [as next] (file:///C:/Users/ASUS/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2736966)\n    at Object.next (file:///C:/Users/ASUS/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:695481)"
  },
  "logs": [
    "2024-06-23T07:07:39.003Z [info]: Logging initialized",
    "2024-06-23T07:07:39.030Z [info]: got ConfigDTO version 0.8, wanted 0.8",
    "2024-06-23T07:07:39.030Z [info]: Versions to Update: ",
    "2024-06-23T07:07:39.038Z [debug]: Undo stack cleared",
    "2024-06-23T07:07:39.083Z [error]: No loader registered for the SAP-icons-v5 icons collection. Probably you forgot to import the \"AllIcons.js\" module for the respective package.",
    "2024-06-23T07:07:39.093Z [info]: Electron API call: window:setZoom\n -- [1]",
    "2024-06-23T07:07:39.158Z [info]: ui5 boot complete",
    "2024-06-23T07:07:39.169Z [debug]: Undo stack cleared",
    "2024-06-23T07:07:39.169Z [info]: Fetching Github releases",
    "2024-06-23T07:07:39.297Z [info]: active page:  -- 0",
    "2024-06-23T07:07:39.298Z [info]: Autosave initialized with 180s interval",
    "2024-06-23T07:07:39.666Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:39.666Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:39.667Z [info]: Electron API call: process:argv\n -- []",
    "2024-06-23T07:07:39.795Z [info]: Got latest release: 0.0.5, current version: 0.0.5",
    "2024-06-23T07:07:40.066Z [warn]: Multiple UI5 Web Components instances detected.\nLoading order (versions before 1.1.0 not listed): \nRuntime 0 - ver 1.19.0\nRuntime 1 - ver 1.22.0-rc.3\n\n\"Runtime 1 - ver 1.22.0-rc.3\" failed to define 1 tag(s) as they were defined by a runtime of an older version \"Runtime 0 - ver 1.19.0\": ui5-icon.\nWARNING! If your code uses features of the above web components, unavailable in Runtime 0 - ver 1.19.0, it might not work as expected!\n\nTo prevent other runtimes from defining tags that you use, consider using scoping or have third-party libraries use scoping: https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/03-scoping.md.",
    "2024-06-23T07:07:40.111Z [warn]: Multiple UI5 Web Components instances detected.\nLoading order (versions before 1.1.0 not listed): \nRuntime 0 - ver 1.19.0\nRuntime 1 - ver 1.22.0-rc.3\n\n\"Runtime 0 - ver 1.19.0\" failed to define 1 tag(s) as they were defined by a runtime of a newer version \"Runtime 1 - ver 1.22.0-rc.3\": ui5-button.\nSince the above web components were defined by the same or newer version runtime, they should be compatible with your code.\n\nTo prevent other runtimes from defining tags that you use, consider using scoping or have third-party libraries use scoping: https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/03-scoping.md.",
    "2024-06-23T07:07:44.109Z [debug]: Undo stack cleared",
    "2024-06-23T07:07:44.114Z [info]: active page:  -- 0",
    "2024-06-23T07:07:44.129Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:44.129Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:59.547Z [info]: Electron API call: file:loadPrompt\n -- [[{\"extensions\":[\"woj\",\"pdf\",\"svg\"],\"name\":\"All Supported Types (.woj/.pdf/.svg)\"},{\"extensions\":[\"woj\"],\"name\":\"Wournal File (Multi-Page) (.woj)\"},{\"extensions\":[\"pdf\"],\"name\":\"Portable Document Format (.pdf)\"},{\"extensions\":[\"svg\"],\"name\":\"Scalable Vector Graphics (Single-Page) (.svg)\"},{\"extensions\":[\"*\"],\"name\":\"All Files\"}]]",
    "2024-06-23T07:07:59.549Z [debug]: Undo stack cleared",
    "2024-06-23T07:07:59.553Z [info]: active page:  -- 0",
    "2024-06-23T07:07:59.554Z [info]: showing dialog with heading {\n  \"completed\": false,\n  \"observers\": [],\n  \"_value\": \"Loading Document\",\n  \"_options\": {\n    \"reflect\": false,\n    \"converter\": {}\n  }\n}",
    "2024-06-23T07:07:59.555Z [info]: <Not Serializable>",
    "2024-06-23T07:07:59.555Z [info]: Dialog",
    "2024-06-23T07:07:59.591Z [info]: Electron API call: shell:addRecentDocument\n -- [\"C:\\\\Users\\\\ASUS\\\\OneDrive\\\\Telegram\\\\(@Amazonebook) A Man Called Ove.pdf\"]",
    "2024-06-23T07:07:59.591Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:59.591Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:07:59.681Z [info]: Electron API call: file:exists\n -- [\"C:\\\\Users\\\\ASUS\\\\OneDrive\\\\Telegram\\\\(@Amazonebook) A Man Called Ove.woj\"]",
    "2024-06-23T07:07:59.694Z [info]: Electron API call: file:read\n -- [\"C:\\\\Users\\\\ASUS\\\\OneDrive\\\\Telegram\\\\(@Amazonebook) A Man Called Ove.pdf\"]",
    "2024-06-23T07:07:59.697Z [debug]: Loading PDF: C:\\Users\\ASUS\\OneDrive\\Telegram\\(@Amazonebook) A Man Called Ove.pdf",
    "2024-06-23T07:08:00.099Z [debug]: Undo stack cleared",
    "2024-06-23T07:08:00.102Z [info]: active page:  -- 0",
    "2024-06-23T07:08:00.185Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:08:00.185Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:08:01.108Z [debug]: Creating PDF Viewer for Page 1",
    "2024-06-23T07:08:01.112Z [debug]: Drawing PDF Viewer for Page 1",
    "2024-06-23T07:08:01.156Z [debug]: Creating PDF Viewer for Page 2",
    "2024-06-23T07:08:01.157Z [debug]: Drawing PDF Viewer for Page 2",
    "2024-06-23T07:08:01.158Z [debug]: Creating PDF Viewer for Page 3",
    "2024-06-23T07:08:01.159Z [debug]: Drawing PDF Viewer for Page 3",
    "2024-06-23T07:08:06.704Z [info]: active page:  -- 1",
    "2024-06-23T07:08:07.241Z [debug]: Creating PDF Viewer for Page 4",
    "2024-06-23T07:08:07.242Z [debug]: Drawing PDF Viewer for Page 4",
    "2024-06-23T07:08:08.987Z [info]: active page:  -- 2",
    "2024-06-23T07:08:09.507Z [debug]: Creating PDF Viewer for Page 5",
    "2024-06-23T07:08:09.507Z [debug]: Drawing PDF Viewer for Page 5",
    "2024-06-23T07:08:10.520Z [info]: active page:  -- 3",
    "2024-06-23T07:08:11.040Z [debug]: Freeing PDF Viewer for Page 1",
    "2024-06-23T07:08:11.041Z [debug]: Creating PDF Viewer for Page 6",
    "2024-06-23T07:08:11.042Z [debug]: Drawing PDF Viewer for Page 6",
    "2024-06-23T07:08:14.142Z [info]: active page:  -- 4",
    "2024-06-23T07:08:14.667Z [debug]: Freeing PDF Viewer for Page 2",
    "2024-06-23T07:08:14.673Z [debug]: Creating PDF Viewer for Page 7",
    "2024-06-23T07:08:14.674Z [debug]: Drawing PDF Viewer for Page 7",
    "2024-06-23T07:08:15.661Z [info]: active page:  -- 5",
    "2024-06-23T07:08:16.182Z [debug]: Freeing PDF Viewer for Page 3",
    "2024-06-23T07:08:16.191Z [debug]: Creating PDF Viewer for Page 8",
    "2024-06-23T07:08:16.192Z [debug]: Drawing PDF Viewer for Page 8",
    "2024-06-23T07:08:18.223Z [info]: active page:  -- 5",
    "2024-06-23T07:08:18.408Z [info]: active page:  -- 5",
    "2024-06-23T07:08:19.023Z [info]: active page:  -- 5",
    "2024-06-23T07:08:19.967Z [info]: active page:  -- 5",
    "2024-06-23T07:08:27.734Z [info]: active page:  -- 5",
    "2024-06-23T07:08:35.821Z [info]: active page:  -- 5",
    "2024-06-23T07:08:40.213Z [info]: active page:  -- 5",
    "2024-06-23T07:08:41.206Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:08:42.921Z [info]: active page:  -- 5",
    "2024-06-23T07:08:43.852Z [info]: active page:  -- 5",
    "2024-06-23T07:08:53.323Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:09:03.301Z [info]: active page:  -- 5",
    "2024-06-23T07:09:09.959Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-23T07:09:11.180Z [info]: active page:  -- 5",
    "2024-06-23T07:09:17.420Z [info]: active page:  -- 5",
    "2024-06-23T07:09:21.453Z [info]: active page:  -- 5",
    "2024-06-23T07:09:26.851Z [info]: active page:  -- 5",
    "2024-06-23T07:09:33.384Z [info]: active page:  -- 5",
    "2024-06-23T07:09:41.326Z [info]: active page:  -- 5",
    "2024-06-23T07:09:50.507Z [info]: showing dialog with heading {\n  \"completed\": false,\n  \"observers\": [],\n  \"_value\": \"Pick a Font\",\n  \"_options\": {\n    \"reflect\": false,\n    \"converter\": {}\n  }\n}",
    "2024-06-23T07:09:50.510Z [info]: <Not Serializable>",
    "2024-06-23T07:09:50.510Z [info]: Dialog",
    "2024-06-23T07:09:58.464Z [info]: active page:  -- 5",
    "2024-06-23T07:09:59.908Z [info]: active page:  -- 5",
    "2024-06-23T07:10:07.694Z [info]: active page:  -- 2",
    "2024-06-23T07:10:07.697Z [info]: active page:  -- 5",
    "2024-06-23T07:10:08.124Z [debug]: Drawing PDF Viewer for Page 4",
    "2024-06-23T07:10:08.126Z [debug]: Drawing PDF Viewer for Page 5",
    "2024-06-23T07:10:08.127Z [debug]: Drawing PDF Viewer for Page 6",
    "2024-06-23T07:10:08.128Z [debug]: Drawing PDF Viewer for Page 7",
    "2024-06-23T07:10:08.130Z [debug]: Drawing PDF Viewer for Page 8"
  ]
}

**Comment by dominiksta** [comment]
Thank you for the bug report! I took the liberty of formatting the message.

I can see from the error message that error occurred when you were trying to undo something. Can you remember what you were trying to undo? That could help me reproduce and hopefully fix the bug. Also, did this happen only once or more often?

**Comment by riyasoni1** [comment]
Hello, I was trying out annotations tools, such as rectangle, line, highlights stuff and later I click undo button continuously to remove all of it, later it threw this error and once I clicked ok, it went to working fine.
