### ISSUE TITLE
Internal Error Details

### ISSUE THREAD

**Issue by hhhhhhh111222** [dominiksta/wournal#13]
```json
{
  "buildInfo": {
    "wournalVersion": "0.0.5",
    "gitVersion": "bd853c1",
    "buildTime": "2024-05-22T13:02:01.525Z",
    "production": true,
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) wournal/0.0.5 Chrome/118.0.5993.159 Electron/27.1.3 Safari/537.36"
  },
  "error": {
    "name": "TypeError",
    "constructor": "TypeError",
    "message": "Cannot read properties of undefined (reading 'annotationLayer')",
    "stack": [
      "TypeError: Cannot read properties of undefined (reading 'annotationLayer')",
      "    at file:///D:/Users/Administrator/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2421282",
      "    at Object.waitNotEq (file:///D:/Users/Administrator/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2504494)",
      "    at WournalPDFPageView.drawOrFree (file:///D:/Users/Administrator/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2421248)",
      "    at async WournalPage.<anonymous> (file:///D:/Users/Administrator/AppData/Local/Programs/Wournal/resources/app.asar/renderer/script/main.js:5:2396993)",
      "    at async Promise.all (index 3)"
    ]
  },
  "logs": [
    "2024-06-29T04:49:31.932Z [info]: Logging initialized",
    "2024-06-29T04:49:31.936Z [info]: got ConfigDTO version 0.8, wanted 0.8",
    "2024-06-29T04:49:31.936Z [info]: Versions to Update: ",
    "2024-06-29T04:49:31.941Z [debug]: Undo stack cleared",
    "2024-06-29T04:49:31.974Z [error]: No loader registered for the SAP-icons-v5 icons collection. Probably you forgot to import the \"AllIcons.js\" module for the respective package.",
    "2024-06-29T04:49:32.017Z [info]: Electron API call: window:setZoom\n -- [1]",
    "2024-06-29T04:49:32.027Z [info]: ui5 boot complete",
    "2024-06-29T04:49:32.031Z [debug]: Undo stack cleared",
    "2024-06-29T04:49:32.032Z [info]: Fetching Github releases",
    "2024-06-29T04:49:32.044Z [info]: D:\\T\\教\\r\\L -- 10",
    "2024-06-29T04:49:32.115Z [info]: active page:  -- 0",
    "2024-06-29T04:49:32.117Z [info]: Autosave initialized with 180s interval",
    "2024-06-29T04:49:32.494Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:32.494Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:32.496Z [info]: Electron API call: process:argv\n -- []",
    "2024-06-29T04:49:32.962Z [warn]: Multiple UI5 Web Components instances detected.\nLoading order (versions before 1.1.0 not listed): \nRuntime 0 - ver 1.19.0\nRuntime 1 - ver 1.22.0-rc.3\n\n\"Runtime 1 - ver 1.22.0-rc.3\" failed to define 1 tag(s) as they were defined by a runtime of an older version \"Runtime 0 - ver 1.19.0\": ui5-icon.\nWARNING! If your code uses features of the above web components, unavailable in Runtime 0 - ver 1.19.0, it might not work as expected!\n\nTo prevent other runtimes from defining tags that you use, consider using scoping or have third-party libraries use scoping: https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/03-scoping.md.",
    "2024-06-29T04:49:33.162Z [info]: Got latest release: 0.0.5, current version: 0.0.5",
    "2024-06-29T04:49:33.213Z [warn]: Multiple UI5 Web Components instances detected.\nLoading order (versions before 1.1.0 not listed): \nRuntime 0 - ver 1.19.0\nRuntime 1 - ver 1.22.0-rc.3\n\n\"Runtime 0 - ver 1.19.0\" failed to define 1 tag(s) as they were defined by a runtime of a newer version \"Runtime 1 - ver 1.22.0-rc.3\": ui5-button.\nSince the above web components were defined by the same or newer version runtime, they should be compatible with your code.\n\nTo prevent other runtimes from defining tags that you use, consider using scoping or have third-party libraries use scoping: https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/03-scoping.md.",
    "2024-06-29T04:49:33.457Z [info]: D:\\T\\教\\r\\L -- 10",
    "2024-06-29T04:49:41.153Z [info]: Electron API call: file:loadPrompt\n -- [[{\"extensions\":[\"woj\",\"pdf\",\"svg\"],\"name\":\"All Supported Types (.woj/.pdf/.svg)\"},{\"extensions\":[\"woj\"],\"name\":\"Wournal File (Multi-Page) (.woj)\"},{\"extensions\":[\"pdf\"],\"name\":\"Portable Document Format (.pdf)\"},{\"extensions\":[\"svg\"],\"name\":\"Scalable Vector Graphics (Single-Page) (.svg)\"},{\"extensions\":[\"*\"],\"name\":\"All Files\"}]]",
    "2024-06-29T04:49:41.157Z [debug]: Undo stack cleared",
    "2024-06-29T04:49:41.169Z [info]: active page:  -- 0",
    "2024-06-29T04:49:41.170Z [info]: showing dialog with heading {\n  \"completed\": false,\n  \"observers\": [],\n  \"_value\": \"Loading Document\",\n  \"_options\": {\n    \"reflect\": false,\n    \"converter\": {}\n  }\n}",
    "2024-06-29T04:49:41.170Z [info]: <Not Serializable>",
    "2024-06-29T04:49:41.170Z [info]: Dialog",
    "2024-06-29T04:49:41.203Z [info]: Electron API call: shell:addRecentDocument\n -- [\"C:\\\\Users\\\\Administrator\\\\Desktop\\\\KW-RE-L3.pdf\"]",
    "2024-06-29T04:49:41.203Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:41.203Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:41.284Z [info]: Electron API call: file:exists\n -- [\"C:\\\\Users\\\\Administrator\\\\Desktop\\\\KW-RE-L3.woj\"]",
    "2024-06-29T04:49:44.894Z [info]: Electron API call: file:read\n -- [\"C:\\\\Users\\\\Administrator\\\\Desktop\\\\KW-RE-L3.pdf\"]",
    "2024-06-29T04:49:45.239Z [debug]: Loading PDF: C:\\Users\\Administrator\\Desktop\\KW-RE-L3.pdf",
    "2024-06-29T04:49:49.803Z [debug]: Undo stack cleared",
    "2024-06-29T04:49:49.808Z [info]: active page:  -- 0",
    "2024-06-29T04:49:49.948Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:49.948Z [info]: Electron API call: window:setTitle\n -- [\"Wournal\"]",
    "2024-06-29T04:49:50.820Z [debug]: Creating PDF Viewer for Page 2",
    "2024-06-29T04:49:50.829Z [debug]: Drawing PDF Viewer for Page 2",
    "2024-06-29T04:49:50.903Z [debug]: Creating PDF Viewer for Page 3",
    "2024-06-29T04:49:50.903Z [debug]: Drawing PDF Viewer for Page 3",
    "2024-06-29T04:49:50.938Z [debug]: Creating PDF Viewer for Page 1",
    "2024-06-29T04:49:50.939Z [debug]: Drawing PDF Viewer for Page 1",
    "2024-06-29T04:49:57.465Z [info]: active page:  -- 1",
    "2024-06-29T04:49:57.978Z [debug]: Creating PDF Viewer for Page 4",
    "2024-06-29T04:49:57.979Z [debug]: Drawing PDF Viewer for Page 4",
    "2024-06-29T04:49:58.234Z [info]: active page:  -- 2",
    "2024-06-29T04:49:58.749Z [debug]: Creating PDF Viewer for Page 5",
    "2024-06-29T04:49:58.750Z [debug]: Drawing PDF Viewer for Page 5",
    "2024-06-29T04:49:59.147Z [info]: active page:  -- 3",
    "2024-06-29T04:49:59.665Z [debug]: Freeing PDF Viewer for Page 1",
    "2024-06-29T04:49:59.666Z [debug]: Creating PDF Viewer for Page 6",
    "2024-06-29T04:49:59.666Z [debug]: Drawing PDF Viewer for Page 6",
    "2024-06-29T04:50:00.079Z [info]: active page:  -- 4",
    "2024-06-29T04:50:00.604Z [debug]: Freeing PDF Viewer for Page 2",
    "2024-06-29T04:50:00.605Z [debug]: Creating PDF Viewer for Page 7",
    "2024-06-29T04:50:00.605Z [debug]: Drawing PDF Viewer for Page 7",
    "2024-06-29T04:50:02.279Z [info]: active page:  -- 5",
    "2024-06-29T04:50:02.463Z [info]: active page:  -- 6",
    "2024-06-29T04:50:02.631Z [info]: active page:  -- 7",
    "2024-06-29T04:50:02.799Z [info]: active page:  -- 8",
    "2024-06-29T04:50:03.000Z [info]: active page:  -- 9",
    "2024-06-29T04:50:03.524Z [debug]: Creating PDF Viewer for Page 10",
    "2024-06-29T04:50:03.524Z [debug]: Drawing PDF Viewer for Page 10",
    "2024-06-29T04:50:03.533Z [debug]: Creating PDF Viewer for Page 11",
    "2024-06-29T04:50:03.533Z [debug]: Drawing PDF Viewer for Page 11",
    "2024-06-29T04:50:03.536Z [debug]: Creating PDF Viewer for Page 12",
    "2024-06-29T04:50:03.536Z [debug]: Drawing PDF Viewer for Page 12",
    "2024-06-29T04:50:03.538Z [debug]: Freeing PDF Viewer for Page 4",
    "2024-06-29T04:50:03.548Z [debug]: Freeing PDF Viewer for Page 5",
    "2024-06-29T04:50:03.548Z [debug]: Freeing PDF Viewer for Page 6",
    "2024-06-29T04:50:03.550Z [debug]: Freeing PDF Viewer for Page 3",
    "2024-06-29T04:50:03.552Z [debug]: Freeing PDF Viewer for Page 7",
    "2024-06-29T04:50:03.586Z [debug]: Creating PDF Viewer for Page 8",
    "2024-06-29T04:50:03.587Z [debug]: Drawing PDF Viewer for Page 8",
    "2024-06-29T04:50:03.588Z [debug]: Creating PDF Viewer for Page 9",
    "2024-06-29T04:50:03.590Z [debug]: Drawing PDF Viewer for Page 9"
  ]
}
```

**Comment by dominiksta** [comment]
Thank you for bringing this up. This was a bug that I was aware of but had forgotten recently. It happened sometimes when one would scroll around in a PDF too fast. It should be fixed with the next release.
