### ISSUE TITLE
Weird Build Error with EPIPE on Debian WSL

### ISSUE THREAD

**Issue by AuroraMaster** [dominiksta/wournal#16]
wsl2 debian12 node18.20.4
after dev
```
git clone https://github.com/dominiksta/wournal/
npm i
npm run dev
```

```
root@Aurora:~/workspace/wournal# npm run dev

> wournal@0.0.8 dev
> npm run start


> wournal@0.0.8 start
> cross-env NODE_ENV=development electron-forge start

✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [0.5s]
✔ Running generateAssets hook
✔ [plugin-webpack] Compiling main process code [0.6s]
⠴ [plugin-webpack] Launching dev servers for renderer process code
root@Aurora:~/workspace/wournal# Error: write EPIPE
at target._send (node:internal/child_process:872:20)
at target.send (node:internal/child_process:745:19)
at /root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
at new Promise (<anonymous>)
at sendMessage (/root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
at /root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
at Generator.next (<anonymous>)
at fulfilled (/root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -32,
code: 'EPIPE',
syscall: 'write'
}
Error: write EPIPE
at target._send (node:internal/child_process:872:20)
at target.send (node:internal/child_process:745:19)
at /root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
at new Promise (<anonymous>)
at sendMessage (/root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
at /root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
at Generator.next (<anonymous>)
at fulfilled (/root/workspace/wournal/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -32,
code: 'EPIPE',
syscall: 'write'
}
```
gpt said maybe port maxbuf overflow ，
Tried increasing buffer size (useless)
Try port (useless)
Try streaming (not implemented)

I don't know what to do anymore, need help

**Comment by dominiksta** [comment]
(Sorry for the late reply, I have been rather busy lately.)
First of all, thank you for considering to contribute to wournal!

This is very odd. I can not reproduce this at all, and google doesn't really point me to anything useful. We are using the same node version, the only difference (which shouldn't matter) is that I am using Windows directly without WSL. I have also tried cloning and running on Ubuntu in WSL2 and that worked as expected.

Can you try running the project under Windows directly without WSL? I could imagine that possibly WLSg (or the X Server you are using) is doing something weird. Can you also confirm that you are not running out of memory?

Maybe potentially possibly perhaps related (but unresolved):
- web-infra-dev/rspack#6905
- strapi/strapi#17994
